name: 'bsky-met-bot post image'

on:
  workflow_dispatch:
  schedule:
    # - cron: "*/30 * * * *"

jobs:
  post:
    name: post
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install TypeScript and ts-node
        run: npm install -g typescript ts-node
        
      - name: Compile TypeScript
        run: npx tsc --outDir dist

      - name: Send post
        env: 
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        run: node dist/index.js  
          randomID=$(node dist/index.js)
          echo "::set-env name=RANDOM_ID::$randomID"
          echo $randomID

      - name: Add randomID to POSTED file
        run: echo $RANDOM_ID >> POSTED
        shell: bash
        if: success() && steps.send_post.outputs.blob_id != ''
